### ISSUE TITLE
Allow user to edit todo

### ISSUE THREAD

**Issue by modous** [modous/Todo-challenge#3]
**Acceptance criteria**
- [x] Input should be not be empty.
- [x] Input should be reset after adding todo.
- [x] Should save on pressing Enter.
- [x] Should cancel on pressing Esc.
- [x] Should save on blur.
- [x] Should reset to old value when saving fails (invalid input).

**API Documentation:**
https://docs.google.com/document/d/1hoY4uB8FhehC4Cy4CbclFpVICtt0DpmOIKyDDtHQeWA/edit?usp=sharing
