### ISSUE TITLE
Show list of todo's

### ISSUE THREAD

**Issue by modous** [modous/Todo-challenge#6]
**Properties**
- todos

**Acceptance criteria**
- [x]  Should have typed properties
- [ ] All passed todos should be rendered as a Badge component.
- [x] Uses `UL` and `LI` elements.
- [x] Build as reusable component.

**Design**
https://www.figma.com/file/RSkpovJvxbFqX2DNoqDiwA/Code-challenge?type=design&node-id=0%3A1&mode=design&t=t9okm2U4NRwEdEdw-1
